### Construir dataset desde Txt

* *pasos* 

* 1- me fijo cómo identificar las películas vs usuarios
* 2- crear del len(df1) un vector con todas las movieids para poder concatenarlo
* 3- Para eso necesito tener una cantidad de iteraciones que corresponde a la cantidad de usuarios que puntuan una pelicula.

Es decir si tengo 

"volver al futuro":
* usuario 1: 5
* usuario 2: 6
* usuario 3: 7

voy a querer que al lado de cada uno de los usuarios diga "volver al futuro". Voy a necesitar contar que cantidad de usuarios hay y poder concatenar el id_movie por esas cantidades y crear un vector del mismo tamaño del dataset original para después apendearlo

In [3]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()


In [4]:
import gc #garbage collector
from playsound import playsound
#!pip install playsound

import time
start_time = time.time()

In [5]:
!ls ../data/netflix-prize-data

README
combined_data_1.txt
combined_data_1_with_movie_id.csv
combined_data_2.txt
combined_data_3.txt
combined_data_4.txt
movie_titles.csv
probe.txt
qualifying.txt


In [6]:
netflix = "..//data//netflix-prize-data//"
figures = "..//figures//"

# mostrar error
# with open(netflix + "movie_titles.csv") as f:
   # print(f)

In [7]:
with open(netflix + "movie_titles.csv") as f:
    print(f)
    #for i in range(10):
    #    print(f.readline())

<_io.TextIOWrapper name='..//data//netflix-prize-data//movie_titles.csv' mode='r' encoding='cp1252'>


# Mostrar txt
# command line vs folder

In [8]:
%%time
def load_data(name):
    df = pd.read_csv(name, header = None, names = ['User','Rating'], usecols = [0,1], encoding='cp1252')
    return df

df1 = load_data(netflix + 'combined_data_1.txt')
print(df1.shape)

(24058263, 2)
Wall time: 31.9 s


In [9]:
df1.head()

User  Rating
0       1:     NaN
1  1488844     3.0
2   822109     5.0
3   885013     4.0
4    30878     4.0

# df1.Rating.isna()

In [10]:
df1.Rating.isna()

0            True
1           False
2           False
3           False
4           False
            ...  
24058258    False
24058259    False
24058260    False
24058261    False
24058262    False
Name: Rating, Length: 24058263, dtype: bool

In [11]:
len(df1[df1.Rating.isna()==True])

4499

In [12]:
df1.User.values

array(['1:', '1488844', '822109', ..., '512536', '988963', '1704416'],
      dtype=object)

# print(len(df1.User[df1.Rating.isna()].values))

In [13]:
print(len(df1.User[df1.Rating.isna()].values))

4499


## Titulo-ID

In [14]:
df_title = pd.read_csv('../data/netflix-prize-data/movie_titles.csv', encoding = "ISO-8859-1",index_col = 0, header = None, usecols = [0,2], names = ['Movie_Id', 'Name'])
df_title.head()

Name
Movie_Id                              
1                      Dinosaur Planet
2           Isle of Man TT 2004 Review
3                            Character
4         Paula Abdul's Get Up & Dance
5             The Rise and Fall of ECW

In [15]:
movie_id = 1
print(df_title.loc[movie_id].Name)

Dinosaur Planet


# movies_ids_df1 = df1.User[df1.Rating.isna()].values

In [16]:
#notar en el head que el id de nivue esta cómo 1: y rating dice nan y el resto son ids de peliculas si no tiene : o rating no tiene nan
movies_ids_df1 = df1.User[df1.Rating.isna()].values #me quedo con los nan como id de las movies
print(movies_ids_df1)
print(len(movies_ids_df1))

['1:' '2:' '3:' ... '4497:' '4498:' '4499:']
4499


#  np.arange(1,len(movies_ids_df1) + 1)

In [17]:
#cambio el formato con numpy pasandolo cómo correspondiente al valor de index+1
movies_ids_df1 = np.arange(1,len(movies_ids_df1) + 1)
print(movies_ids_df1) #ahora tengo las ids de las movies y luego el listado de los usuarios

[   1    2    3 ... 4497 4498 4499]


# Crear dataset df1_nan
# df1_nan = df1_nan[df1_nan['Rating'] == True

In [18]:
##############################-----------------************* todo este bloque se hace solo para sacar los idx_movies de abajo
#fijate que filtras los nan del rating nada más
df1_nan = pd.DataFrame(pd.isnull(df1.Rating))
 #condicion pd.isnull , fijate que arriba lo de values lo hice solo para mostrarte y bueno definir que era el idmovies
df1_nan = df1_nan[df1_nan['Rating'] == True] #quiero entonces trabajar sobre el datase df1

In [19]:


#indice
idx_movies_ids = df1_nan.index.values
print(idx_movies_ids) #defino los valores nulos de rating como el indice del filtro df1_nan

[       0      548      694 ... 24056849 24057564 24057834]


In [23]:
 np.append(idx_movies_ids,df1.shape[0])

array([       0,      548,      694, ..., 24057834, 24058263, 24058263],
      dtype=int64)

In [25]:
idx_movies_ids

array([       0,      548,      694, ..., 24057564, 24057834, 24058263],
      dtype=int64)

In [22]:
np.diff(idx_movies_ids)

array([ 548,  146, 2013, ...,  715,  270,  429], dtype=int64)

In [29]:
df1.shape[0]

24058263

In [20]:
idx_movies_ids = np.append(idx_movies_ids,df1.shape[0]) #al apendearlo
cantidad_criticas = np.diff(idx_movies_ids) #puedo tener la diferencia para contar??
cantidad_criticas

array([ 548,  146, 2013, ...,  715,  270,  429], dtype=int64)

# Excel para explicar como relleno la np.array y np.full

In [21]:
##estoy construyendo la matriz cantidad de criticas por película
columna_movie_id = np.array([])
for i in range(cantidad_criticas.size): #size cuenta las peliculas
    aux = np.full(cantidad_criticas[i], movies_ids_df1[i]) #np.full crea una matriz compuesta entre cantidad de peliculas que saque de size y los movie id
    columna_movie_id = np.concatenate((columna_movie_id, aux))

In [24]:
cantidad_criticas[1]

146

In [25]:
movies_ids_df1[1]

2

In [26]:
columna_movie_id[1]

1.0

In [27]:
df1['Movie_id'] = columna_movie_id
df1

User  Rating  Movie_id
0              1:     NaN       1.0
1         1488844     3.0       1.0
2          822109     5.0       1.0
3          885013     4.0       1.0
4           30878     4.0       1.0
...           ...     ...       ...
24058258  2591364     2.0    4499.0
24058259  1791000     2.0    4499.0
24058260   512536     5.0    4499.0
24058261   988963     3.0    4499.0
24058262  1704416     3.0    4499.0

[24058263 rows x 3 columns]

In [28]:
#df1.to_csv(netflix + 'combined_data_1_with_movie_id.csv', index= False)

In [30]:
print("--- %s segundos---" % (time.time() - start_time))
gc.collect()

--- 382.0550515651703 segundos---


20

In [31]:
playsound(figures+"war.mp3")


In [16]:
df1 = pd.read_csv(netflix + 'combined_data_1_with_movie_id.csv', dtype={'Rating': np.int8, 'movie_id': np.int16})


In [17]:
df1.head()

User  Rating  Movie_id
0  1488844       3         1
1   822109       5         1
2   885013       4         1
3    30878       4         1
4   823519       3         1

In [23]:
long_tail = pd.DataFrame()

In [28]:
long_tail = df1.groupby('Movie_id').agg({'Rating': [np.size, np.mean]})
long_tail

Rating          
           size      mean
Movie_id                 
1           547  3.749543
2           145  3.558621
3          2012  3.641153
4           142  2.739437
5          1140  3.919298
...         ...       ...
4495        614  3.478827
4496       9519  3.763000
4497        714  2.715686
4498        269  2.464684
4499        428  2.614486

[4499 rows x 2 columns]